### ISSUE TITLE
PRs into caffeine-ng/caffeine-ng?

### ISSUE THREAD

**Issue by WhyNotHugo** [PF4Public/caffeine-ng#1]
Hey! I noticed your comment about this fork on GitLab recently (I'm gradually moving all my stuff over to GitHub though).

I wouldn't mind accepting PRs with fixes into [caffeine-ng/caffeine-ng](https://github.com/caffeine-ng/caffeine-ng) if you'd rather not maintain an additional fork.

Also, I don't really have access to Ubuntu-like machines in general, so it's kind of a hassle for me to test there, generally, so I'd really appreciate a hand with that, if you're willing.

Cheers!

**Comment by PF4Public** [comment]
Shame on me, I didn't find your caffeine repository here on Github :( 
Or it wasn't there when I was searching...

I will gladly submit my PRs to your repo if _it is to be maintained_ (I notice that last change to your caffeine-ng repo was a year ago, hence this fork).  I have a feature request in mind even ;)

Buuuuuut....
Yeah, here goes the _but_ thing. You may freely inspect my changes and what do you find there?
What do you think about changing wording like this: 73fb38ff941e2ea2d9ac7cfb65a36215fcb5e784 . I personally feel very uncomfortable with the original wording. 
I did also a "wonderful" fix of some scripts, which might be unaceptable for you (cae6ba3c74d901d3a67c521810a6136f940256bb ). 
What do we do with this _buts_? The first one in particular.

TBH I would readily not maintain yet another fork, especially given that its Python codebase, which is not the language of preference for me, but there **must** be a caffeine-ng, which is usable and comfortable to me (at least). **This one** suits me. Should you reject wording changes, I have to maintain my own. Rather properly forking it off of yours this time.

What do you think of this?

**Comment by WhyNotHugo** [comment]
It's possible that it wasn't there while you were searching :stuck_out_tongue: 

TBH, I mostly maintain it for bugfixes, but welcome new features and alike.

Both linked commits look good to me. The only commit that'd odd to me is `ade83e7`, since most Linux distros seem to install packages into `/usr/bin` (though I understand that that's not universal, and that BSDs don't tend to do that). Maybe the package for distributions that use `/usr/local/bin` could patch that bit?

Personally, I just prefer to have a single `caffeine-ng` to avoid duplicating effort in future, plus, someone extra willing to help maintain is always welcome. :wink:

**Comment by WhyNotHugo** [comment]
I've pushed most changes into caffeine-ng, and pushed v3.4.2.

Feel free to push PRs my way if you have any more changes. :)
